trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: ./run_tests.sh
  displayName: 'Run tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'
